-- Database: user_service

-- DROP DATABASE IF EXISTS user_service;

CREATE DATABASE user_service
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'English_United States.1252'
    LC_CTYPE = 'English_United States.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

-- Creating the departments table
CREATE TABLE departments (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL
);

-- Creating the divisions table
CREATE TABLE divisions (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    department_id INTEGER REFERENCES departments(id) ON DELETE CASCADE
);

-- Creating the users table
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    hashed_password VARCHAR(255) NOT NULL,
    department_id INTEGER REFERENCES departments(id) ON DELETE SET NULL,
    division_id INTEGER REFERENCES divisions(id) ON DELETE SET NULL
);


-- example data generated by AI
-- Insert example departments
INSERT INTO departments (name) VALUES
    ('Human Resources'),
    ('Information Technology'),
    ('Finance'),
    ('Marketing'),
    ('Sales');

-- Insert example divisions
INSERT INTO divisions (name, department_id) VALUES
    ('Recruitment', 1),  -- Recruitment division in Human Resources
    ('IT Support', 2),    -- IT Support division in Information Technology
    ('Development', 2),   -- Development division in Information Technology
    ('Accounting', 3),    -- Accounting division in Finance
    ('Digital Marketing', 4), -- Digital Marketing division in Marketing
    ('Field Sales', 5);    -- Field Sales division in Sales

-- Insert example users
INSERT INTO users (name, email, hashed_password, department_id, division_id) VALUES
    ('Alice Johnson', 'alice.johnson@example.com', 'hashedpassword1', 1, 1),
    ('Bob Smith', 'bob.smith@example.com', 'hashedpassword2', 2, 2),
    ('Carol White', 'carol.white@example.com', 'hashedpassword3', 2, 3),
    ('David Brown', 'david.brown@example.com', 'hashedpassword4', 3, 4),
    ('Eva Green', 'eva.green@example.com', 'hashedpassword5', 4, 5),
    ('Frank Black', 'frank.black@example.com', 'hashedpassword6', 5, 6);
