-- Creating the divisions table
CREATE TABLE divisions (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

-- Creating the departments table
CREATE TABLE departments (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    division_id INTEGER REFERENCES divisions(id) ON DELETE CASCADE
);

-- Creating the users table
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    hashed_password VARCHAR(255) NOT NULL,
    department_id INTEGER REFERENCES departments(id) ON DELETE SET NULL,
    division_id INTEGER REFERENCES divisions(id) ON DELETE SET NULL
);


-- example data generated by AI

-- Insert example divisions
INSERT INTO divisions (name) VALUES
    ('HR'),  
    ('IT'), 
    ('Production Management'),  
    ('Accounting'),   
    ('Sales');   

-- Insert example departments
INSERT INTO departments (name, division_id) VALUES
    ('HR',1),
    ('IT',2),
    ('Import Export',3),
    ('Accounting',4),
    ('Sales',5);


-- Insert example users
INSERT INTO users (name, email, hashed_password, department_id) VALUES
    ('Alice Johnson', 'alice.johnson@example.com', 'hashedpassword1', 1),
    ('Bob Smith', 'bob.smith@example.com', 'hashedpassword2', 2),
    ('Carol White', 'carol.white@example.com', 'hashedpassword3', 3),
    ('David Brown', 'david.brown@example.com', 'hashedpassword4', 4),
    ('Eva Green', 'eva.green@example.com', 'hashedpassword5', 5),
    ('Frank Black', 'frank.black@example.com', 'hashedpassword6', 2);
